[
  {
    "name": "London",
    "local_names": {
      "no": "London",
      "feature_name": "London",
      "ie": "London",
      "ar": "لندن",
      "cs": "Londýn",
      "tk": "London",
      "he": "לונדון",
      "de": "London",
      "af": "Londen",
      "sq": "Londra",
      "sv": "London",
      "ne": "लन्डन",
      "tw": "London",
      "sk": "Londýn",
      "is": "London",
      "pl": "Londyn",
      "gl": "Londres",
      "gn": "Lóndyre",
      "it": "Londra",
      "lt": "Londonas",
      "bg": "Лондон",
      "io": "London",
      "hr": "London",
      "eo": "Londono",
      "sh": "London",
      "os": "Лондон",
      "ro": "Londra",
      "zh": "伦敦",
      "ja": "ロンドン",
      "az": "London",
      "fo": "London",
      "da": "London",
      "ka": "ლონდონი",
      "km": "ឡុងដ៍",
      "bh": "लंदन",
      "fr": "Londres",
      "nv": "Tooh Dineʼé Bikin Haalʼá",
      "et": "London",
      "mg": "Lôndôna",
      "ko": "런던",
      "cv": "Лондон",
      "cy": "Llundain",
      "ms": "London",
      "ga": "Londain",
      "kw": "Loundres",
      "br": "Londrez",
      "lv": "Londona",
      "ff": "London",
      "tg": "Лондон",
      "uz": "London",
      "bm": "London",
      "vo": "London",
      "kk": "Лондон",
      "uk": "Лондон",
      "wo": "Londar",
      "lb": "London",
      "om": "Landan",
      "ha": "Landan",
      "qu": "London",
      "ig": "London",
      "bn": "লন্ডন",
      "ny": "London",
      "el": "Λονδίνο",
      "ay": "London",
      "ca": "Londres",
      "hy": "Լոնդոն",
      "fj": "Lodoni",
      "ku": "London",
      "hu": "London",
      "fa": "لندن",
      "fy": "Londen",
      "eu": "Londres",
      "fi": "Lontoo",
      "id": "London",
      "zu": "ILondon",
      "pt": "Londres",
      "sd": "لنڊن",
      "ps": "لندن",
      "ce": "Лондон",
      "ur": "علاقہ لندن",
      "gv": "Lunnin",
      "li": "Londe",
      "be": "Лондан",
      "yi": "לאנדאן",
      "es": "Londres",
      "bi": "London",
      "ug": "لوندۇن",
      "rm": "Londra",
      "ht": "Lonn",
      "sr": "Лондон",
      "kn": "ಲಂಡನ್",
      "to": "Lonitoni",
      "ta": "இலண்டன்",
      "tt": "Лондон",
      "mi": "Rānana",
      "ru": "Лондон",
      "tr": "Londra",
      "or": "ଲଣ୍ଡନ",
      "yo": "Lọndọnu",
      "si": "ලන්ඩන්",
      "mt": "Londra",
      "na": "London",
      "sw": "London",
      "av": "Лондон",
      "se": "London",
      "oc": "Londres",
      "st": "London",
      "gu": "લંડન",
      "mk": "Лондон",
      "so": "London",
      "ascii": "London",
      "sm": "Lonetona",
      "en": "London",
      "ln": "Lóndɛlɛ",
      "vi": "Luân Đôn",
      "su": "London",
      "hi": "लंदन",
      "bo": "ལོན་ཊོན།",
      "ee": "London",
      "gd": "Lunnainn",
      "nn": "London",
      "th": "ลอนดอน",
      "wa": "Londe",
      "cu": "Лондонъ",
      "am": "ለንደን",
      "sn": "London",
      "nl": "Londen",
      "ab": "Лондон",
      "sa": "लन्डन्",
      "co": "Londra",
      "an": "Londres",
      "mr": "लंडन",
      "ky": "Лондон",
      "mn": "Лондон",
      "te": "లండన్",
      "pa": "ਲੰਡਨ",
      "ia": "London",
      "sl": "London",
      "my": "လန်ဒန်မြို့",
      "kv": "Лондон",
      "tl": "Londres",
      "jv": "London",
      "sc": "Londra",
      "ml": "ലണ്ടൻ",
      "lo": "ລອນດອນ",
      "ba": "Лондон",
      "bs": "London",
      "kl": "London"
    },
    "lat": 51.5073219,
    "lon": -0.1276474,
    "country": "GB",
    "state": "England"
  },
  {
    "name": "City of London",
    "local_names": {
      "zh": "倫敦市",
      "en": "City of London",
      "es": "City de Londres",
      "ru": "Сити",
      "he": "הסיטי של לונדון",
      "ur": "لندن شہر",
      "lt": "Londono Sitis",
      "uk": "Лондонське Сіті",
      "pt": "Cidade de Londres",
      "fr": "Cité de Londres",
      "hi": "सिटी ऑफ़ लंदन",
      "ko": "시티 오브 런던"
    },
    "lat": 51.5156177,
    "lon": -0.0919983,
    "country": "GB",
    "state": "England"
  },
  {
    "name": "London",
    "local_names": {
      "bn": "লন্ডন",
      "ko": "런던",
      "hy": "Լոնտոն",
      "ja": "ロンドン",
      "ug": "لوندۇن",
      "fr": "London",
      "oj": "Baketigweyaang",
      "en": "London",
      "be": "Лондан",
      "el": "Λόντον",
      "ar": "لندن",
      "ru": "Лондон",
      "ka": "ლონდონი",
      "lv": "Landona",
      "fa": "لندن",
      "iu": "ᓚᓐᑕᓐ",
      "th": "ลอนดอน",
      "he": "לונדון",
      "lt": "Londonas",
      "ga": "Londain",
      "yi": "לאנדאן",
      "cr": "ᓬᐊᐣᑕᐣ"
    },
    "lat": 42.9832406,
    "lon": -81.243372,
    "country": "CA",
    "state": "Ontario"
  },
  {
    "name": "Chelsea",
    "local_names": {
      "it": "Chelsea",
      "eu": "Chelsea",
      "ar": "تشيلسي",
      "en": "Chelsea",
      "el": "Τσέλσι",
      "ru": "Челси",
      "hu": "Chelsea",
      "ja": "チェルシー",
      "sk": "Chelsea",
      "fr": "Chelsea",
      "fa": "چلسی",
      "et": "Chelsea",
      "sh": "Chelsea, London",
      "sv": "Chelsea, London",
      "he": "צ'לסי",
      "es": "Chelsea",
      "de": "Chelsea",
      "nl": "Chelsea",
      "az": "Çelsi",
      "tr": "Chelsea, Londra",
      "ko": "첼시",
      "pt": "Chelsea",
      "hi": "चेल्सी, लंदन",
      "ga": "Chelsea",
      "ur": "چیلسی، لندن",
      "pl": "Chelsea",
      "uk": "Челсі",
      "zh": "車路士",
      "da": "Chelsea",
      "id": "Chelsea, London",
      "no": "Chelsea",
      "af": "Chelsea, Londen",
      "vi": "Chelsea, Luân Đôn"
    },
    "lat": 51.4875167,
    "lon": -0.1687007,
    "country": "GB",
    "state": "England"
  },
  {
    "name": "London",
    "lat": 37.1289771,
    "lon": -84.0832646,
    "country": "US",
    "state": "Kentucky"
  }
]